# Generated by Django 4.1.3 on 2022-11-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_to_image',
            field=models.CharField(default='Insert URL here', max_length=255),
        ),
    ]
